Fixed✅
error code to SSL tls issues fixed

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,1 +1,87 @@
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
+
+header() {
+  echo "" || true
+  echo "-----> $*" || true
+}
+
+export_env_dir() {
+  env_dir=$1
+  acceptlist_regex=${2:-''}
+  denylist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+  if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+      echo "$e" | grep -E "$acceptlist_regex" | grep -qvE "$denylist_regex" &&
+      export "$e=$(cat $env_dir/$e)"
+      :
+    done
+  fi
+}
+
+output() {
+  while IFS= read -r LINE; do
+    # do not indent headers that are being piped through the output
+    if [[ "$LINE" =~ ^-----\>.* ]]; then
+      echo "$LINE" || true
+    else
+      echo "       $LINE" || true
+    fi
+  done
+}
+
+header "Installing ffmpeg"
+
+BUILD_DIR=${1:-}
+VENDOR_DIR="vendor"
+ENV_DIR=${3:-}
+FFMPEG_ARCHIVE_NAME="ffmpeg.tar.xz"
+
+export_env_dir $ENV_DIR
+
+cd $BUILD_DIR
+mkdir -p $VENDOR_DIR
+cd $VENDOR_DIR
+mkdir -p ffmpeg
+cd ffmpeg
+
+if [[ -z $FFMPEG_DOWNLOAD_URL ]]; then
+  echo "Variable FFMPEG_DOWNLOAD_URL isn't set, using default value" | output
+  
+  # OLD URL NOT WORKING FROM HEROKU DUE TO SSL ISSUES
+  # FFMPEG_DOWNLOAD_URL="https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
+
+  # TEMP URL / FEEL FREE TO POINT IT TO YOUR OWN FILE
+  FFMPEG_DOWNLOAD_URL="https://cookycookstaging.s3.amazonaws.com/ffmpeg-git-amd64-static.tar.xz"
+fi
+
+echo "Downloading $FFMPEG_DOWNLOAD_URL" | output
+
+echo "testing insecure"
+echo "testing tls max 1.2"
+echo "insecure"
+
+code=$(curl "$FFMPEG_DOWNLOAD_URL" --insecure --fail --retry 5 --retry-max-time 15 -o ./$FFMPEG_ARCHIVE_NAME --write-out "%{http_code}")
+
+echo "http_code is $code"
+
+if [ "$code" != "200" ]; then
+  echo "Unable to download ffmpeg: $code" | output && exit 1
+fi
+
+echo "Unpacking the archive" | output
+
+tar xJf "./$FFMPEG_ARCHIVE_NAME" --strip-components=1
+
+if [ "$?" != "0" ]; then
+  echo "Failed to unpack" | output && exit 1
+fi
+
+rm $FFMPEG_ARCHIVE_NAME
+
+PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
+mkdir -p $(dirname $PROFILE_PATH)
+echo 'export PATH="$PATH:${HOME}/vendor/ffmpeg"' >> $PROFILE_PATH
+
+echo "Installation successful" | output
 
